<?php

use Illuminate\Database\Seeder;
use App\Freelancer;
class FreelancerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Freelancer::create([
            'user_id'=>61,
            'facebook' =>'www.facebook.com',
            'email' =>'aaa@gmail.com',
            'website'=>'www.google.com',
            'googleplus'=>'aa@findix.co.jp',
            'twitter'=>'aaa',
            'linkedin'=>'aaa',
            'freelancer_url'=>'',
            'date_of_birth'=>'2020-09-10',
            'nrc'=>'12/mmm(n)11111',
            'address'=>'Yangon',
            'location_id'=>2,
            'current_work_status'=>'Junior Developer',
            'description'=>'aaaa',
            'total_experiences'=>3,
            'freelancer_status_id'=>1, 
            'company_id'=>1,
            'freelancer_company' =>'Findix Myanmar',
            'category_id' =>4
        ]);
        Freelancer::create([
            'user_id'=>62,
            'facebook' =>'www.facebook.com',
            'email' =>'bbb@gmail.com',
            'website'=>'www.google.com',
            'googleplus'=>'bb@findix.co.jp',
            'twitter'=>'bbb',
            'linkedin'=>'bbb',
            'freelancer_url'=>'',
            'date_of_birth'=>'2020-09-10',
            'nrc'=>'12/mmm(n)22222',
            'address'=>'Yangon',
            'location_id'=>2,
            'current_work_status'=>'Junior Developer',
            'description'=>'aaaa',
            'total_experiences'=>3,
            'freelancer_status_id'=>2, 
            'company_id'=>1,
            'freelancer_company' =>'Findix Myanmar',
            'category_id' =>4
        ]);
        Freelancer::create([
            'user_id'=>63,
            'facebook' =>'www.facebook.com',
            'email' =>'bbb@gmail.com',
            'website'=>'www.google.com',
            'googleplus'=>'bb@findix.co.jp',
            'twitter'=>'bbb',
            'linkedin'=>'bbb',
            'freelancer_url'=>'',
            'date_of_birth'=>'2020-09-10',
            'nrc'=>'12/mmm(n)22222',
            'address'=>'Yangon',
            'location_id'=>1,
            'current_work_status'=>'Senior Developer',
            'description'=>'aaaa',
            'total_experiences'=>3,
            'freelancer_status_id'=>3, 
            'company_id'=>1,
            'freelancer_company' =>'Findix Myanmar',
            'category_id' =>4
        ]);
        Freelancer::create([
            'user_id'=>64,
            'facebook' =>'www.facebook.com',
            'email' =>'bbb@gmail.com',
            'website'=>'www.google.com',
            'googleplus'=>'bb@findix.co.jp',
            'twitter'=>'bbb',
            'linkedin'=>'bbb',
            'freelancer_url'=>'',
            'date_of_birth'=>'2020-09-10',
            'nrc'=>'12/mmm(n)22222',
            'address'=>'Yangon',
            'location_id'=>3,
            'current_work_status'=>'Project Leader',
            'description'=>'aaaa',
            'total_experiences'=>3,
            'freelancer_status_id'=>3, 
            'company_id'=>1,
            'freelancer_company' =>'Findix Myanmar',
            'category_id' =>4
        ]);
        Freelancer::create([
            'user_id'=>65,
            'facebook' =>'www.facebook.com',
            'email' =>'bbb@gmail.com',
            'website'=>'www.google.com',
            'googleplus'=>'bb@findix.co.jp',
            'twitter'=>'bbb',
            'linkedin'=>'bbb',
            'freelancer_url'=>'',
            'date_of_birth'=>'2020-09-10',
            'nrc'=>'12/mmm(n)22222',
            'address'=>'Yangon',
            'location_id'=>3,
            'current_work_status'=>'Project Manager',
            'description'=>'aaaa',
            'total_experiences'=>3,
            'freelancer_status_id'=>4, 
            'company_id'=>1,
            'freelancer_company' =>'Findix Myanmar',
            'category_id' =>4
        ]);
         Freelancer::create([
            'user_id'=>66,
            'facebook' =>'www.facebook.com',
            'email' =>'aaa@gmail.com',
            'website'=>'www.google.com',
            'googleplus'=>'aa@findix.co.jp',
            'twitter'=>'aaa',
            'linkedin'=>'aaa',
            'freelancer_url'=>'',
            'date_of_birth'=>'2020-09-10',
            'nrc'=>'12/mmm(n)11111',
            'address'=>'Yangon',
            'location_id'=>2,
            'current_work_status'=>'Junior Developer',
            'description'=>'aaaa',
            'total_experiences'=>3,
            'freelancer_status_id'=>1, 
            'company_id'=>1,
            'freelancer_company' =>'Findix Myanmar',
            'category_id' =>4
         ]);
        Freelancer::create([
            'user_id'=>67,
            'facebook' =>'www.facebook.com',
            'email' =>'bbb@gmail.com',
            'website'=>'www.google.com',
            'googleplus'=>'bb@findix.co.jp',
            'twitter'=>'bbb',
            'linkedin'=>'bbb',
            'freelancer_url'=>'',
            'date_of_birth'=>'2020-09-10',
            'nrc'=>'12/mmm(n)22222',
            'address'=>'Yangon',
            'location_id'=>2,
            'current_work_status'=>'Junior Developer',
            'description'=>'aaaa',
            'total_experiences'=>3,
            'freelancer_status_id'=>2, 
            'company_id'=>1,
            'freelancer_company' =>'Findix Myanmar',
            'category_id' =>4
        ]);
        Freelancer::create([
            'user_id'=>68,
            'facebook' =>'www.facebook.com',
            'email' =>'bbb@gmail.com',
            'website'=>'www.google.com',
            'googleplus'=>'bb@findix.co.jp',
            'twitter'=>'bbb',
            'linkedin'=>'bbb',
            'freelancer_url'=>'',
            'date_of_birth'=>'2020-09-10',
            'nrc'=>'12/mmm(n)22222',
            'address'=>'Yangon',
            'location_id'=>1,
            'current_work_status'=>'Senior Developer',
            'description'=>'aaaa',
            'total_experiences'=>3,
            'freelancer_status_id'=>3, 
            'company_id'=>1,
            'freelancer_company' =>'Findix Myanmar',
            'category_id' =>4
        ]);
        Freelancer::create([
            'user_id'=>69,
            'facebook' =>'www.facebook.com',
            'email' =>'bbb@gmail.com',
            'website'=>'www.google.com',
            'googleplus'=>'bb@findix.co.jp',
            'twitter'=>'bbb',
            'linkedin'=>'bbb',
            'freelancer_url'=>'',
            'date_of_birth'=>'2020-09-10',
            'nrc'=>'12/mmm(n)22222',
            'address'=>'Yangon',
            'location_id'=>3,
            'current_work_status'=>'Project Leader',
            'description'=>'aaaa',
            'total_experiences'=>3,
            'freelancer_status_id'=>3, 
            'company_id'=>1,
            'freelancer_company' =>'Findix Myanmar',
            'category_id' =>4
        ]);
        Freelancer::create([
            'user_id'=>70,
            'facebook' =>'www.facebook.com',
            'email' =>'bbb@gmail.com',
            'website'=>'www.google.com',
            'googleplus'=>'bb@findix.co.jp',
            'twitter'=>'bbb',
            'linkedin'=>'bbb',
            'freelancer_url'=>'',
            'date_of_birth'=>'2020-09-10',
            'nrc'=>'12/mmm(n)22222',
            'address'=>'Yangon',
            'location_id'=>3,
            'current_work_status'=>'Project Manager',
            'description'=>'aaaa',
            'total_experiences'=>3,
            'freelancer_status_id'=>4, 
            'company_id'=>1,
            'freelancer_company' =>'Findix Myanmar',
            'category_id' =>4
        ]);
         Freelancer::create([
            'user_id'=>71,
            'facebook' =>'www.facebook.com',
            'email' =>'aaa@gmail.com',
            'website'=>'www.google.com',
            'googleplus'=>'aa@findix.co.jp',
            'twitter'=>'aaa',
            'linkedin'=>'aaa',
            'freelancer_url'=>'',
            'date_of_birth'=>'2020-09-10',
            'nrc'=>'12/mmm(n)11111',
            'address'=>'Yangon',
            'location_id'=>2,
            'current_work_status'=>'Junior Developer',
            'description'=>'aaaa',
            'total_experiences'=>3,
            'freelancer_status_id'=>1, 
            'company_id'=>1,
            'freelancer_company' =>'Findix Myanmar',
            'category_id' =>4
        ]);
        Freelancer::create([
            'user_id'=>72,
            'facebook' =>'www.facebook.com',
            'email' =>'bbb@gmail.com',
            'website'=>'www.google.com',
            'googleplus'=>'bb@findix.co.jp',
            'twitter'=>'bbb',
            'linkedin'=>'bbb',
            'freelancer_url'=>'',
            'date_of_birth'=>'2020-09-10',
            'nrc'=>'12/mmm(n)22222',
            'address'=>'Yangon',
            'location_id'=>2,
            'current_work_status'=>'Junior Developer',
            'description'=>'aaaa',
            'total_experiences'=>3,
            'freelancer_status_id'=>2, 
            'company_id'=>1,
            'freelancer_company' =>'Findix Myanmar',
            'category_id' =>4
        ]);
        Freelancer::create([
            'user_id'=>73,
            'facebook' =>'www.facebook.com',
            'email' =>'bbb@gmail.com',
            'website'=>'www.google.com',
            'googleplus'=>'bb@findix.co.jp',
            'twitter'=>'bbb',
            'linkedin'=>'bbb',
            'freelancer_url'=>'',
            'date_of_birth'=>'2020-09-10',
            'nrc'=>'12/mmm(n)22222',
            'address'=>'Yangon',
            'location_id'=>1,
            'current_work_status'=>'Senior Developer',
            'description'=>'aaaa',
            'total_experiences'=>3,
            'freelancer_status_id'=>3, 
            'company_id'=>1,
            'freelancer_company' =>'Findix Myanmar',
            'category_id' =>4
        ]);
        Freelancer::create([
            'user_id'=>74,
            'facebook' =>'www.facebook.com',
            'email' =>'bbb@gmail.com',
            'website'=>'www.google.com',
            'googleplus'=>'bb@findix.co.jp',
            'twitter'=>'bbb',
            'linkedin'=>'bbb',
            'freelancer_url'=>'',
            'date_of_birth'=>'2020-09-10',
            'nrc'=>'12/mmm(n)22222',
            'address'=>'Yangon',
            'location_id'=>3,
            'current_work_status'=>'Project Leader',
            'description'=>'aaaa',
            'total_experiences'=>3,
            'freelancer_status_id'=>3, 
            'company_id'=>1,
            'freelancer_company' =>'Findix Myanmar',
            'category_id' =>4
        ]);
        Freelancer::create([
            'user_id'=>75,
            'facebook' =>'www.facebook.com',
            'email' =>'bbb@gmail.com',
            'website'=>'www.google.com',
            'googleplus'=>'bb@findix.co.jp',
            'twitter'=>'bbb',
            'linkedin'=>'bbb',
            'freelancer_url'=>'',
            'date_of_birth'=>'2020-09-10',
            'nrc'=>'12/mmm(n)22222',
            'address'=>'Yangon',
            'location_id'=>3,
            'current_work_status'=>'Project Manager',
            'description'=>'aaaa',
            'total_experiences'=>3,
            'freelancer_status_id'=>4, 
            'company_id'=>1,
            'freelancer_company' =>'Findix Myanmar',
            'category_id' =>4
        ]);
       
    }
}
